name: Feature Request
description: Suggest an idea for this project
labels: [":zap: enhancement"]
body:
  - type: markdown
    attributes:
      value: |-
        Thanks for suggesting an improvement to Cucumber! 💖

        Use the questions below to help explain why you think this change is needed.
  - type: textarea
    id: problem
    attributes:
      label: 🤔 What's the problem you're trying to solve?
      description: >
        A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: ✨ What's your proposed solution?
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: ⛏ Have you considered any alternatives or workarounds?
      description: >
        A clear and concise description of any alternative solutions or features
        you've considered.
  - type: textarea
    id: context
    attributes:
      label: 📚 Any additional context?
      description: >
        Add any other context, references or screenshots about the feature request here.
  - type: markdown
    attributes:
      value: |-
        *This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.yaml)*

